# Generated by Django 2.0.2 on 2018-07-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180731_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmento',
            old_name='depto',
            new_name='title',
        ),
    ]
