# Generated by Django 2.0.2 on 2018-07-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180731_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
