# Generated by Django 2.0.2 on 2018-07-31 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180731_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Departmento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='escolaridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Escolaridad', verbose_name='Escolaridad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Genero', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Municipio', verbose_name='Municipio'),
        ),
    ]
