# Generated by Django 2.0.2 on 2018-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180731_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zona',
            field=models.IntegerField(null=True, verbose_name='Zona'),
        ),
    ]
