# Generated by Django 2.0.2 on 2018-07-31 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180731_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='departmento',
        ),
    ]
