# Generated by Django 2.0.2 on 2018-07-23 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Fecha de muerte')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('date_of_admission', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('available', models.IntegerField(default=0, verbose_name='Disponibles')),
                ('location', models.CharField(max_length=250, verbose_name='ubicacion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Author', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paices',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un Genero', max_length=200)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Bibliteca')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('ubication', models.CharField(max_length=200, verbose_name='Direccion')),
                ('latitud', models.CharField(max_length=200, verbose_name='latitud')),
                ('longitud', models.CharField(max_length=200, verbose_name='longitud')),
            ],
            options={
                'verbose_name': 'Libraria',
                'verbose_name_plural': 'Librerias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Book', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='estado')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.State', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Genre', verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ManyToManyField(to='catalog.Library', verbose_name='Biblioteca'),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Countries', verbose_name='Pais'),
        ),
    ]
