# Generated by Django 2.0.2 on 2018-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180724_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tokem',
            field=models.CharField(default='dY431nA5RxeKAZpR', max_length=16, verbose_name='Token'),
        ),
    ]
