# Generated by Django 2.0.2 on 2018-07-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180731_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tokem',
            field=models.CharField(default='ztjEhNNNX2kQBqxy', max_length=16, verbose_name='Token'),
        ),
    ]
