# Generated by Django 2.0.2 on 2018-08-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180731_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='seleccionado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tokem',
            field=models.CharField(default='9Kyv1N1rUk9a4BL6', max_length=16, verbose_name='Token'),
        ),
    ]
