# Generated by Django 2.0.2 on 2018-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180801_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tokem',
            field=models.CharField(default='cEvRFHnnBU]KFNEA', max_length=16, verbose_name='Token'),
        ),
    ]
