# Generated by Django 2.0.2 on 2018-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180801_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tokem',
            field=models.CharField(default='xU7sBP7TNv3GMASN', max_length=16, verbose_name='Token'),
        ),
    ]
