# Generated by Django 2.0.2 on 2018-08-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180801_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='tokem',
            field=models.CharField(default='cxnCv]5ps1pkq6A6', max_length=16, verbose_name='Token'),
        ),
    ]
